### ISSUE TITLE
FAQs to be uploaded for now

### ISSUE THREAD

**Issue by Mcoppola16x** [greghunt/knowledge#24]
Where is this building going to located?

This building is going to be on the Valhalla Montreal Co-op land located 20 minutes outside of downtown Montreal, Quebec, Canada. We have begun to transform about 5 out of 60+ acres of what use to be GMO corn and soya fields into an organic food production paradise and a open to the public learning centre.

Why do you need 500,000$?

Well to build a school there is an enormous amount of resources and talent that we need to be a part of the entire project. Not only does it cost a good amount to build the building but all the rewards and educational materials including documenting and filming the entire process - the creation of ebooks and online classes and materials and the large crew we will need to prepare and coordinate the entire build throughout the season is enormous. This money is going to pay the bare minimum of expenses we will need to get this school up and running and will allow us the opportunity to begin teaching students year round from here on out.

Will your plans be open source in the future?

In short yes. We want to open the plans up to public and allow for more and more collaborators to partake in the process of designing and upgrading the buildings. However until the prototype is built and we are able to test all elements of our design and improve upon the entire process internally we want to ensure the quality control of these designs being open source kicks off at what we feel is an optimum level for widespread adoption. Although we the team of architects engineers and other experts that partake in our team have designed buildings like this before - releasing the plans before having tested them ourselves in the physical seems unwise!

We will open the doors soon we just want to ensure we do it at the right moment!

Do you guys offer financing for larger reward options?

Yes. We would be happy to find a way to accommodate some different financial options for rewards but rewards although some rewards must be paid in full before purchase. For more information or questions concerning such email explore(at)buildyourwisdom.com and let us know how we can help!

What happens if you don’t reach your target?

Well for the most part we have to. Some way some how we will reach that goal and we are trying to do it via crowdsourcing because that will allow us to not have any debt related to this building and therefore we can run it as a wide open school with much lower pricing then if we had some large anvil of a mortgage hanging over our head.

Are you accepting & looking for sponsors or partners?

Yes we are - although we would only accept partnerships and agreements with organizations we feel truly share our collective values.

Will these buildings work in all climates?

With modifications yes. The principles of passive buildings can work anywhere in the world but obviously the various climates of the world are unique depending on where you are on the planet. In some scenarios these buildings will need more insulation, in others less. This is a much larger question of course in many ways and one of the ideas we will address directly in our classes.

**Comment by melanieleduc** [comment]
CAN I COME VISIT VALHALLA?

YES! We are always happy to receive curious open minded people to come and explore everything from our Permaculture Gardens – Earthship greenhouse – our off grid technology systems and meet the crew! If you’re in Montreal you can always come visit us on the land during our season on Saturdays between 10 am and 5pm! Our season runs from April 1st to October 31st and all are welcome without appointment during those times! We do a potluck lunch on Saturdays including pizza so bring some goodies for others and there won’t be a lack of food… You can learn more about Valhalla Montreal and our farming co-op here [http://www.valhallamontreal.com/].


WHERE CAN I LEARN MORE IF I STILL HAVE QUESTIONS?
The best way would be to message Valhalla or Wisdom at explore@valhallamovement.com or explore@BuildYourWisdom.com. Due to the large volume of emails we receive we will might have a backlog and 48 hour wait before some replies – but don’t worry we pride ourselves in answering all our emails! P.S. If you’re in Montreal you can always come visit us on the land during our season on Saturdays between 10 am and 5pm! Our season runs from April 1st to October 31st and all are welcome without appointment during those times!

**Comment by melanieleduc** [comment]
So I added all of this to the project but it is not showing up. Perhaps a cache issue. Greg can you look into it? 


CODE:

<div id="accordion" class="panel-group">
<div class="panel panel-default">
<div id="headingOne" class="panel-heading">
<h4 class="panel-title"><a href="#collapseOne" data-toggle="collapse" data-parent="#accordion"><br />
Want to learn more about our ecovillage intentions?<br />
</a></h4>
</div>
<div id="collapseOne" class="panel-collapse collapse in">
<div class="panel-body">
<p>If we had a seed for every time we got questions about this - we would be in quite the dense forest.</p>
<p>Our intentions from day 1 at Valhalla (even before it had a name) was to build a school and a community. Our dream is to build the homes and spaces we wish past generations had put forth in their design of the spaces. We want roads to give way to paths in food forests - for homes to be integrated into nature and its inhabitants to be encouraged to spend more time outdoors and connected to the ins and outs within their household.</p>
<p>Our dream is to have 30 or so off grid homes that display the potential of what suburbia could look like and for a community of 150 people or so to be able to live off of the land entirely if they ose. Most of the 60+ acres of land would be protected as a park and farm space where we will take the building of communal grounds for our neighborhood into our own hands and not wait for government to do it for us.</p>
<p>We want to be and DO the change we want to see in the world.</p>
</div>
</div>
</div>
<div class="panel panel-default">
<div id="headingFour" class="panel-heading">
<h4 class="panel-title"><a href="#collapseFour" data-toggle="collapse" data-parent="#accordion"><br />
Where is this building going to located?<br />
</a></h4>
</div>
<div id="collapseFour" class="panel-collapse collapse in">
<div class="panel-body">
<p>This building is going to be on the Valhalla Montreal Co-op land located 20 minutes outside of downtown Montreal, Quebec, Canada. We have begun to transform about 5 out of 60+ acres of what use to be GMO corn and soya fields into an organic food production paradise and a open to the public learning centre.</p>
</div>
</div>
</div>
<div class="panel panel-default">
<div id="headingFive" class="panel-heading">
<h4 class="panel-title"><a href="#collapseFive" data-toggle="collapse" data-parent="#accordion"><br />
Why do you need 500,000$?<br />
</a></h4>
</div>
<div id="collapseFive" class="panel-collapse collapse in">
<div class="panel-body">
<p>Well to build a school there is an enormous amount of resources and talent that we need to be a part of the entire project. Not only does it cost a good amount to build the building but all the rewards and educational materials including documenting and filming the entire process - the creation of ebooks and online classes and materials and the large crew we will need to prepare and coordinate the entire build throughout the season is enormous. This money is going to pay the bare minimum of expenses we will need to get this school up and running and will allow us the opportunity to begin teaching students year round from here on out.</p>
</div>
</div>
</div>
<div class="panel panel-default">
<div id="headingSix" class="panel-heading">
<h4 class="panel-title"><a href="#collapseSix" data-toggle="collapse" data-parent="#accordion"><br />
Will your plans be open source in the future?<br />
</a></h4>
</div>
<div id="collapseSix" class="panel-collapse collapse in">
<div class="panel-body">
<p>In short yes. We want to open the plans up to public and allow for more and more collaborators to partake in the process of designing and upgrading the buildings. However until the prototype is built and we are able to test all elements of our design and improve upon the entire process internally we want to ensure the quality control of these designs being open source kicks off at what we feel is an optimum level for widespread adoption. Although we the team of architects engineers and other experts that partake in our team have designed buildings like this before - releasing the plans before having tested them ourselves in the physical seems unwise!</p>
<p>We will open the doors soon we just want to ensure we do it at the right moment!</p>
</div>
</div>
</div>
<div class="panel panel-default">
<div id="headingSeven" class="panel-heading">
<h4 class="panel-title"><a href="#collapseSeven" data-toggle="collapse" data-parent="#accordion"><br />
Do you guys offer financing for larger reward options?<br />
</a></h4>
</div>
<div id="collapseSeven" class="panel-collapse collapse in">
<div class="panel-body">
<p>Yes. We would be happy to find a way to accommodate some different financial options for rewards but rewards although some rewards must be paid in full before purchase. For more information or questions concerning such email explore(at)buildyourwisdom.com and let us know how we can help!</p>
</div>
</div>
</div>
<div class="panel panel-default">
<div id="headingEight" class="panel-heading">
<h4 class="panel-title"><a href="#collapseEight" data-toggle="collapse" data-parent="#accordion"><br />
What happens if you don’t reach your target?<br />
</a></h4>
</div>
<div id="collapseEight" class="panel-collapse collapse in">
<div class="panel-body">
<p>Well for the most part we have to. Some way some how we will reach that goal and we are trying to do it via crowdsourcing because that will allow us to not have any debt related to this building and therefore we can run it as a wide open school with much lower pricing then if we had some large anvil of a mortgage hanging over our head.</p>
</div>
</div>
</div>
<div class="panel panel-default">
<div id="headingNine" class="panel-heading">
<h4 class="panel-title"><a href="#collapseNine" data-toggle="collapse" data-parent="#accordion"><br />
Are you accepting & looking for sponsors or partners?<br />
</a></h4>
</div>
<div id="collapseNine" class="panel-collapse collapse in">
<div class="panel-body">
<p>Yes we are - although we would only accept partnerships and agreements with organizations we feel truly share our collective values.</p>
</div>
</div>
</div>
<div class="panel panel-default">
<div id="headingTen" class="panel-heading">
<h4 class="panel-title"><a href="#collapseTen" data-toggle="collapse" data-parent="#accordion"><br />
Will these buildings work in all climates?<br />
</a></h4>
</div>
<div id="collapseTen" class="panel-collapse collapse in">
<div class="panel-body">
<p>With modifications yes. The principles of passive buildings can work anywhere in the world but obviously the various climates of the world are unique depending on where you are on the planet. In some scenarios these buildings will need more insulation, in others less. This is a much larger question of course in many ways and one of the ideas we will address directly in our classes.</p>
</div>
</div>
</div>
<div class="panel panel-default">
<div id="headingEleven" class="panel-heading">
<h4 class="panel-title"><a href="#collapseEleven" data-toggle="collapse" data-parent="#accordion"><br />
Can I come visit Valhalla?<br />
</a></h4>
</div>
<div id="collapseEleven" class="panel-collapse collapse in">
<div class="panel-body">
<p>YES! We are always happy to receive curious open minded people to come and explore everything from our Permaculture Gardens – Earthship greenhouse – our off grid technology systems and meet the crew! If you’re in Montreal you can always come visit us on the land during our season on Saturdays between 10 am and 5pm! Our season runs from April 1st to October 31st and all are welcome without appointment during those times! We do a potluck lunch on Saturdays including pizza so bring some goodies for others and there won’t be a lack of food… You can learn more about Valhalla Montreal and our farming co-op here [http://www.valhallamontreal.com/].</p>
</div>
</div>
</div>
<div class="panel panel-default">
<div id="headingTwelve" class="panel-heading">
<h4 class="panel-title"><a href="#collapseTwelve" data-toggle="collapse" data-parent="#accordion"><br />
Where can I learn more if I still have question?<br />
</a></h4>
</div>
<div id="collapseTwelve" class="panel-collapse collapse in">
<div class="panel-body">
<p>The best way would be to message Valhalla or Wisdom at explore@valhallamovement.com or explore@BuildYourWisdom.com. Due to the large volume of emails we receive we will might have a backlog and 48 hour wait before some replies – but don’t worry we pride ourselves in answering all our emails! P.S. If you’re in Montreal you can always come visit us on the land during our season on Saturdays between 10 am and 5pm! Our season runs from April 1st to October 31st and all are welcome without appointment during those times!</p>
</div>
</div>
</div>

**Comment by greghunt** [comment]
These need to be hardcoded in, I will add.
